language: node_js
node_js:
  - "6.9"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
git:
  depth: 1

before_script:
  - npm install -g firebase-tools

script:
  - ng build --prod --output-path dist --base-href eshop

after_success:
  - cp dist/index.html dist/404.html
  - firebase deploy --token $FIREBASE_TOKEN

deploy:
  name : Kafil Nasdami
  email: kafil.nasdami@gmail.com
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  # fqdn: www.kafil.xyz
  on:
    branch: develop
